## How to get this result?

### Question 1:

In [17]:
x = ['a','b']

How to get the following output after creating x variable?
```
['a','b','c']
```

In [18]:
x.append('c')
x

['a', 'b', 'c']

### Question 2:

In [49]:
x = ['a','b','k','v','c','j','i','d','e','n','a','s','m','h']
x[0]+x[9]

'an'

How to print 
`kavin` and `anish` after creating the above x variable? 

In [51]:
print(x[2]+x[0]+x[3]+x[6]+x[9])

print(x[0]+x[9]+x[-8]+x[-3]+x[-1])

kavin
anish


In [52]:
kname = x[2]+x[0]+x[3]+x[6]+x[9]
kname.title()

# aname = x[0]+x[-5]+x[-8]+x[-3]+x[-1]
# aname.title()

'Kavin'

### Question 3:

In [36]:
import numpy as np
x = np.array([10,12, 14, 21, 16, 17, 20, 19, 0])

In [39]:
x = np.array([10,12, 14, 21, 16, 17, 20, 19,0])
x
true_or_false = x > 16 
print(true_or_false)
x[true_or_false]

[ True  True  True False  True False False False  True]


array([10, 12, 14, 16,  0])

without running the above code tell me what the following command will output?
```
x_s = x[x < 16]
```

In [10]:
x_s = x[ x < 16 ]
x < 16

array([ True,  True,  True, False, False, False, False])

### Comment 1: How to print a type that belongs to no type?

In [11]:
p = None
print(type(p))

<class 'NoneType'>


### Question 4: 

In [42]:
m = np.array([1,4, 10])
n = 3

# [1, 4, 10]
# [3, 3, 3]

print( m*n )
m*n



[ 3 12 30]


array([ 3, 12, 30])

What will the following command ouput?

```print(m*n)```

In [15]:
print(m*n)

[ 3 12 30]


### Question 5: 

In [ ]:
## what will be the output for the following commmand?

In [43]:
a = [1,2,3]
b = ['b','a','l','a','j','i']
c = [1,0,1]

c + a + b
# write a code to output this following line

# [1, 0, 1] [1, 2, 3] ['b', 'a', 'l', 'a', 'j', 'i']

[1, 0, 1, 1, 2, 3, 'b', 'a', 'l', 'a', 'j', 'i']

In [ ]:
# which one is a legit variable
# Myvar  my_var  _myvar my-var


In [21]:
# How to create integer number variable?

# how to create a float number variable


# python file extension

# variable type 

# trim white space 
# trim()  or strip()



# Compare two values
#  2 == 3 

# 2 > 10

# 10 < 14



def my_add(x, y):
    return(x + y)


In [22]:
my_add(1,2)

3